
//setup all actions needed for the inventory service management :
export const SET_INVENTORY_DATA = 'SET_INVENTORY_DATA';
export const GET_INVENTORY_DATA = 'GET_INVENTORY_DATA';
export const SET_SEARCH_QUERY = 'SET_SEARCH_QUERY';
export const CLEAR_SEARCH_QUERY = 'CLEAR_SEARCH_QUERY';
export const SET_SELECTED_INVENTORY = 'SET_SELECTED_INVENTORY';
export const GET_SELECTED_INVENTORY = 'GET_SELECTED_INVENTORY';
export const SET_TOTAL_CUSTOMERS = 'SET_TOTAL_CUSTOMERS';
export const SET_TOTAL_PRODUCTS = 'SET_TOTAL_PRODUCTS';
export const SET_TOTAL_SALES = 'SET_TOTAL_SALES';
export const SET_TOTAL_STOCKS = 'SET_TOTAL_STOCKS';
export const SET_TOTAL_VENDORS = 'SET_TOTAL_VENDORS';
export const SET_TOTAL_INVENTORY = 'SET_TOTAL_INVENTORY';
export const CLEAR_SELECTED_INVENTORY = 'CLEAR_SELECTED_INVENTORY';
export const ADD_INVENTORY = 'ADD_INVENTORY';
export const UPDATE_INVENTORY = 'UPDATE_INVENTORY';
export const ADD_CUSTOMER_DB = 'ADD_CUSTOMER_DB';
export const ADD_PRODUCT_DB = 'ADD_PRODUCT_DB';
export const ADD_SALE_DB = 'ADD_SALE_DB';
export const ADD_STOCK_DB = 'ADD_STOCK_DB';
export const ADD_VENDOR_DB = 'ADD_VENDOR_DB';
export const ADD_SUPPLIER_DB = 'ADD_SUPPLIER_DB';
export const REMOVE_INVENTORY = 'REMOVE_INVENTORY';