export const SET_PRODUCT_DATA = "SET_PRODUCT_DATA";
export const GET_PRODUCT_DATA = "GET_PRODUCT_DATA";
export const SET_SEARCH_QUERY = "SET_SEARCH_QUERY";
export const CLEAR_SEARCH_QUERY = "CLEAR_SEARCH_QUERY";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const EDIT_PRODUCT = "EDIT_PRODUCT";