// setup all actions needed to use the Order Store : 
export const SET_ORDER_DATA = "SET_ORDER_DATA";
export const GET_ORDER_DATA = "GET_ORDER_DATA";
export const SET_SEARCH_QUERY = "SET_SEARCH_QUERY";
export const CLEAR_SEARCH_QUERY = "CLEAR_SEARCH_QUERY";
export const SET_SELECTED_ORDER = "SET_SELECTED_ORDER";
export const GET_SELECTED_ORDER = "GET_SELECTED_ORDER";
export const SET_CUSTOMER_PARENT = "SET_CUSTOMER_PARENT";
export const GET_CUSTOMER_PARENT = "GET_CUSTOMER_PARENT";
export const SET_INVENTORY_PARENT = "SET_INVENTORY_PARENT";
export const GET_INVENTORY_PARENT = "GET_INVENTORY_PARENT";
